USE [master]
GO

/****** Object:  Database [Proyecto]    Script Date: 11/7/2023 18:44:01 ******/
CREATE DATABASE [Proyecto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Proyecto', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Proyecto.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Proyecto_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Proyecto_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Proyecto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Proyecto] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Proyecto] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Proyecto] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Proyecto] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Proyecto] SET ARITHABORT OFF 
GO

ALTER DATABASE [Proyecto] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Proyecto] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Proyecto] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Proyecto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Proyecto] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Proyecto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Proyecto] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Proyecto] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Proyecto] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Proyecto] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Proyecto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Proyecto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Proyecto] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Proyecto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Proyecto] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Proyecto] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Proyecto] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Proyecto] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Proyecto] SET  MULTI_USER 
GO

ALTER DATABASE [Proyecto] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Proyecto] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Proyecto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Proyecto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Proyecto] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Proyecto] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Proyecto] SET QUERY_STORE = ON
GO

ALTER DATABASE [Proyecto] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Proyecto] SET  READ_WRITE 
GO

